name: Build RwModLoader

on: [push]

jobs:
  build:
    name: Build .NET assemblies
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Compile projects
      run: ./publish.sh
    - name: Zip manual install
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ManualInstall.zip ManualInstall/*
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: |
          UserInstaller.exe
          ManualInstall.zip
    - name: Upload release
      if: startsWith(github.ref, 'refs/tags/0.' )
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        files: |
          UserInstaller.exe
          ManualInstall.zip
