name: Build RwModLoader

on: [push, pull_request]

jobs:
  build:
    name: Build .NET assemblies
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build VirtualEnums
      run: dotnet build VirtualEnums -c Release --no-restore
    - name: Build Realm
      run: dotnet build Realm -c Release --no-restore
    - name: Package Mutator
      run: dotnet publish Mutator -c Release -f net6.0 -r win-x64 --self-contained -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:TrimMode=link -p:TrimmerDefaultAction=link
    - name: Create UserInstaller
      run: mv "Mutator/bin/Release/net6.0/win-x64/publish/Mutator.exe" "UserInstaller.exe"
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: installer-artifacts
        path: UserInstaller.exe
  prerelease:
    name: Create pre-release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: installer-artifacts
      - name: Get previous tag
        id: previoustag
        uses: oprypin/find-latest-tag@v1.1.0
        with:
          repository: ${{ github.repository }}
          releases-only: true
      - name: Create new tag
        id: newtag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.newtag.outputs.new_tag }}
          release_name: Release ${{ steps.newtag.outputs.new_tag }}
          body: |
            **Full Changelog**: https://github.com/Dual-Iron/RwModLoader/compare/${{ steps.previoustag.outputs.tag }}...${{ steps.newtag.outputs.new_tag }}
            
            To install, download and run the `UserInstaller.exe` file.
          draft: false
          prerelease: true
      - name: Upload release assets
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the create_release step above, referencing its ID to get its `outputs` object containing `upload_url`
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: UserInstaller.exe
          asset_name: UserInstaller.exe
          asset_content_type: application/vnd.microsoft.portable-executable
