name: .NET

on:
  push:
    branches: [ collab-friendly ]
  pull_request:
    branches: [ collab-friendly ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build VirtualEnums
      run: dotnet build VirtualEnums -c Release --no-restore
    - name: Build Realm
      run: dotnet build Realm -c Release --no-restore
    - name: Build and publish Mutator
      run: dotnet publish Mutator -c Release -f net6.0 -r win-x64 --no-restore --self-contained -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:TrimMode=link -p:TrimmerDefaultAction=link
    - uses: actions/upload-artifact@v2
      with:
        name: UserInstaller.dll
        path: Mutator/bin/Release/net6.0/win-x64/publish/Mutator.exe
